// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SocialAnimal interface {
	IsSocialAnimal()
}

type Dog struct {
	Name    string         `json:"name"`
	Friends []SocialAnimal `json:"friends"`
}

func (Dog) IsSocialAnimal() {}

type User struct {
	ID         int            `json:"id"`
	Name       string         `json:"name"`
	Age        int            `json:"age"`
	BestFriend *User          `json:"bestFriend"`
	Friends    []SocialAnimal `json:"friends"`
}

func (User) IsSocialAnimal() {}
